version: "3.8"
services:
  preferencias-api:
    build: .
    ports:
      - "8082:80"
    env_file:
      - .env
    depends_on:
      - dynamodb-local
    networks:
      - prefnet

  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - prefnet

networks:
  prefnet:
