version: '3.8'

services:
  auth-db:
    image: postgres:15
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-service:
    build: .
    container_name: auth-service
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - auth-db
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: auth-db
      DB_PORT: 5432
      DB_DATABASE: auth_db
      JWT_SECRET: miclaveultrasecreta
      PORT: 3001
    volumes:
      - .:/app
    working_dir: /app
    command: npm start

volumes:
  auth_data:
