version: '3.8'

services:
  auth-service:
    image: auth-service
    build:
      context: ../auth-service
    ports:
      - "3001:3001"
    environment:
      # tus variables de entorno

  auth-front:
    build: .
    container_name: auth-front
    ports:
      - "80:80"
    depends_on:
      - auth-service
