version: "3.8"
services:
  address-api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - address-db
    networks:
      - addressnet

  address-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: addressdb
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - addressnet

volumes:
  mysql-data:

networks:
  addressnet:
