name: CI - Address Service

on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main, test]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
            MYSQL_ROOT_PASSWORD: ${{ secrets.ADDRESS_DB_PASSWORD }}
            MYSQL_DATABASE: ${{ secrets.ADDRESS_DB_NAME }}    
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java y Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Crear archivo .env
        working-directory: autenticación/address-service
        run: |
          echo "DB_HOST=${{ secrets.ADDRESS_DB_HOST }}" > .env
          echo "DB_PORT=${{ secrets.ADDRESS_DB_PORT }}" >> .env
          echo "DB_USER=${{ secrets.ADDRESS_DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.ADDRESS_DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.ADDRESS_DB_NAME }}" >> .env

      - name: Construir proyecto con Maven
        working-directory: autenticación/address-service
        run: ./mvnw clean package -DskipTests
