name: CI - Address Service

on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main, test]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.ADDRESS_DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.ADDRESS_DB_NAME }}
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java y Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Crear archivo .env
        working-directory: autenticación/address-service
        run: |
          echo "SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3307/${{ secrets.ADDRESS_DB_NAME }}" > .env
          echo "SPRING_DATASOURCE_USERNAME=root" >> .env
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.ADDRESS_DB_PASSWORD }}" >> .env
          echo "JWT_SECRET=miclavesecreta" >> .env

      - name: Dar permisos al wrapper de Maven
        working-directory: autenticación/address-service
        run: chmod +x mvnw

      - name: Construir proyecto con Maven
        working-directory: autenticación/address-service
        run: ./mvnw clean package -DskipTests
