name: CI - Category Service

on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main, test]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.CATEGORY_DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.CATEGORY_DB_NAME }}
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Crear archivo .env
        working-directory: productos/category-service
        run: |
          echo "DB_HOST=localhost" > .env
          echo "DB_PORT=3307" >> .env
          echo "DB_USER=${{ secrets.CATEGORY_DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.CATEGORY_DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.CATEGORY_DB_NAME }}" >> .env
          echo "PORT=3002" >> .env

      - name: Instalar dependencias
        working-directory: productos/category-service
        run: npm install

      - name: Ejecutar prueba básica
        working-directory: productos/category-service
        run: node -e "require('./src/app')"
