name: Despliegue EcomVida User Profile Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Desplegar en EC2 vía SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AUTH_EC2_HOST_PROD }}
        username: ${{ secrets.AUTH_EC2_USER_PROD }}
        key: ${{ secrets.AUTH_EC2_SSH_KEY_PROD }}
        script: |
          # Elimina contenedor antiguo del microservicio si existe
          docker rm -f user-profile || true

          # Clona o actualiza el repositorio
          cd ~/EcomVida-V1.0 || git clone https://github.com/BrieLy07/EcomVida-V1.0.git ~/EcomVida-V1.0
          cd ~/EcomVida-V1.0
          git fetch origin
          git checkout test3
          git pull origin test3

          # -----------------------------------
          # BACKEND: user-profile-service
          # -----------------------------------
          cd backend/autenticacion/user-profile-service
          docker build -t user-profile .
          docker run -d --name user-profile -p 3002:3002 --env-file .env user-profile
