name: Deploy UserProfileService to EC2

on:
  push:
    branches:
      - test2
    paths:
      - 'vida/autenticacion/user-profile-service/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Acceso por SSH y despliegue en EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AUTH_EC2_HOST }}
          username: ${{ secrets.AUTH_EC2_USER }}
          key: ${{ secrets.AUTH_EC2_SSH_KEY }}
          script: |
            cd ~/ecomvida/vida/autenticacion/user-profile-service
            git pull origin test2
            docker-compose down
            docker-compose up -d --build
