name: CI - Product Image Service

on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main, test]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Levantar MinIO manualmente
        run: |
          docker run -d \
            -p 9000:9000 \
            --name minio \
            -e MINIO_ACCESS_KEY=minioadmin \
            -e MINIO_SECRET_KEY=minioadmin \
            minio/minio server /data

      - name: Crear archivo .env
        working-directory: productos/product-image-service
        run: |
          echo "MINIO_ENDPOINT=${{ secrets.IMAGE_MINIO_ENDPOINT }}" > .env
          echo "MINIO_ACCESS_KEY=${{ secrets.IMAGE_MINIO_ACCESS_KEY }}" >> .env
          echo "MINIO_SECRET_KEY=${{ secrets.IMAGE_MINIO_SECRET_KEY }}" >> .env
          echo "MINIO_BUCKET=${{ secrets.IMAGE_MINIO_BUCKET }}" >> .env
          echo "REDIS_ADDR=${{ secrets.IMAGE_REDIS_ADDR }}" >> .env

      - name: Build Docker Image
        working-directory: productos/product-image-service
        run: docker build -t image-api .

      - name: Verificar build
        run: echo "Build completado correctamente"
