name: CI - Product Variant Service

on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main, test]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27028:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Crear archivo .env
        working-directory: productos/product-variant-service
        run: |
          echo "MONGO_URI=${{ secrets.VARIANT_MONGO_URI }}" > .env
          echo "MONGO_DB=${{ secrets.VARIANT_MONGO_DB }}" >> .env

      - name: Instalar PHP, extensión MongoDB y Composer
        run: |
          sudo apt-get update
          sudo apt-get install -y php php-cli php-dev php-pear php-mbstring unzip git curl pkg-config libssl-dev
          sudo pecl install mongodb-1.21.1
          echo "extension=mongodb.so" | sudo tee -a $(php -i | grep 'Loaded Configuration File' | awk '{print $5}')
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Instalar dependencias PHP
        working-directory: productos/product-variant-service
        run: composer install --no-interaction
