name: CI - Product Variant Service

on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main, test]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27028:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    container:
      image: ghcr.io/mlocati/docker-php-extension-installer:php8.2-cli

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar extensión MongoDB y Composer
        run: |
          install-php-extensions mongodb
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer

      - name: Crear archivo .env
        working-directory: productos/product-variant-service
        run: |
          echo "MONGO_URI=${{ secrets.VARIANT_MONGO_URI }}" > .env
          echo "MONGO_DB=${{ secrets.VARIANT_MONGO_DB }}" >> .env

      - name: Instalar dependencias
        working-directory: productos/product-variant-service
        run: composer install --no-interaction
