name: CI - User Preferences Service

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Instalar dependencias
        working-directory: autenticación/user-preferences-service
        run: |
          composer install

      - name: Crear .env local para testing
        working-directory: autenticación/user-preferences-service
        run: |
          echo "AWS_REGION=us-west-2" > .env
          echo "AWS_ACCESS_KEY_ID=test" >> .env
          echo "AWS_SECRET_ACCESS_KEY=test" >> .env
          echo "DYNAMODB_ENDPOINT=http://localhost:8000" >> .env
          echo "DYNAMODB_TABLE=preferencias_usuario" >> .env
          echo "JWT_SECRET=miclavesecreta" >> .env

      - name: Validar sintaxis PHP
        working-directory: autenticación/user-preferences-service
        run: |
          php -l src/index.php
          php -l src/dynamo.php
