name: CI - User Profile Service

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.stats()'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      MONGO_URI: ${{ secrets.PROFILE_MONGO_URI }}
      DB_NAME: ${{ secrets.PROFILE_DB_NAME }}
      JWT_SECRET: ${{ secrets.PROFILE_JWT_SECRET }}

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Instalar dependencias
        working-directory: autenticación/user-profile-service
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Validar ejecución
        working-directory: autenticación/user-profile-service
        run: |
          python src/main.py &
          sleep 5
